# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/PyramidTech/5-Design_Document/LwIP/TFTP/ZyboZ7-20_TFTPserver/ZyboZ7-20_TFTPserver.srcs/sources_1/bd/tftp_bd/ip/tftp_bd_processing_system7_0_0/tftp_bd_processing_system7_0_0.xci
# IP: The module: 'tftp_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PyramidTech/5-Design_Document/LwIP/TFTP/ZyboZ7-20_TFTPserver/ZyboZ7-20_TFTPserver.srcs/sources_1/bd/tftp_bd/ip/tftp_bd_processing_system7_0_0/tftp_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tftp_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/PyramidTech/5-Design_Document/LwIP/TFTP/ZyboZ7-20_TFTPserver/ZyboZ7-20_TFTPserver.srcs/sources_1/bd/tftp_bd/ip/tftp_bd_processing_system7_0_0/tftp_bd_processing_system7_0_0.xci
# IP: The module: 'tftp_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PyramidTech/5-Design_Document/LwIP/TFTP/ZyboZ7-20_TFTPserver/ZyboZ7-20_TFTPserver.srcs/sources_1/bd/tftp_bd/ip/tftp_bd_processing_system7_0_0/tftp_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tftp_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
