# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/tftp_bd/tftp_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tftp_bd || ORIG_REF_NAME==tftp_bd} -quiet] -quiet

# IP: bd/tftp_bd/ip/tftp_bd_processing_system7_0_0/tftp_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tftp_bd_processing_system7_0_0 || ORIG_REF_NAME==tftp_bd_processing_system7_0_0} -quiet] -quiet

# XDC: bd/tftp_bd/tftp_bd_ooc.xdc
